# ReadTheDocs Configuration File
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, programming language and version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "20"
  jobs:
    post_create_environment:
      # Install latest pip + wheel for faster builds
      - pip install --upgrade pip wheel
    post_install:
      # Install Node.js dependencies for any JavaScript examples
      - npm ci || echo "No package.json found, skipping npm install"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
formats:
  - pdf
  - epub
  - htmlzip

# Submodules to include (if any)
submodules:
  include: []
  exclude: all

# Additional search configuration
search:
  ranking:
    api/: 2
    getting-started/: 3
    user-guide/: 1
  ignore:
    - 404.html